setwd("/Users/LSun/Dropbox/Projects/ash_warnings/data")
par(mfrow=c(1,3))
betahat_3<-scan("betahat_3.txt")
plot(density(betahat_3),main="betahat_3")
betahat_3<-scan("betahat_3_1.txt")
plot(density(betahat_3),main="betahat_3_1")
betahat_3<-scan("betahat_3_2.txt")
plot(density(betahat_3),main="betahat_3_2")

par(mfrow=c(1,3))
betahat_8<-scan("betahat_8.txt")
plot(density(betahat_3),main="betahat_8")
betahat_8<-scan("betahat_8_1.txt")
plot(density(betahat_3),main="betahat_8_1")
betahat_8<-scan("betahat_8_2.txt")
plot(density(betahat_3),main="betahat_8_2")

par(mfrow=c(1,3))
betahat_12<-scan("betahat_12.txt")
plot(density(betahat_3),main="betahat_12")
betahat_12<-scan("betahat_12_1.txt")
plot(density(betahat_3),main="betahat_12_1")
betahat_12<-scan("betahat_12_2.txt")
plot(density(betahat_3),main="betahat_12_2")

par(mfrow=c(1,3))
betahat_13<-scan("betahat_13.txt")
plot(density(betahat_3),main="betahat_13")
betahat_13<-scan("betahat_13_1.txt")
plot(density(betahat_3),main="betahat_13_1")
betahat_13<-scan("betahat_13_2.txt")
plot(density(betahat_3),main="betahat_13_2")
